INSERT INTO author(name,surname) values ('Adam','Nowakowski');
INSERT INTO author(name,surname) values ('Sebastian','Nowakowski');
INSERT INTO author(name,surname) values ('Adam','Nowak');
INSERT INTO author(name,surname) values ('Adam','Cichon ');
INSERT INTO author(name,surname) values ('Darek','Nowakowski');
INSERT INTO author(name,surname) values ('Adam','Nowakowski');
INSERT INTO author(name,surname) values ('Arek','Nowak');
INSERT INTO author(name,surname) values ('Adam','Nowakowski');
INSERT INTO author(name,surname) values ('Adam','Kowol');
INSERT INTO author(name,surname) values ('Adam','Kowalski');